// packages/svelte/src/components/Card.svelte
<script lang="ts">
  import { getCardClass } from "@sua-marca-ui/core";

  export let hover = false;
  export let interactive = false;
  $: classes = getCardClass({ hover, interactive });
</script>

<article class={classes}>
  <header class="sm-card__header"><slot name="header" /></header>
  <div class="sm-card__body"><slot /></div>
</article>

// packages/react/src/components/Card/Card.tsx
import * as React from "react";
import { getCardClass } from "@sua-marca-ui/core";

type CardProps = React.HTMLAttributes<HTMLDivElement> & {
  hover?: boolean;
  interactive?: boolean;
};

export const Card = React.forwardRef<HTMLDivElement, CardProps>(function Card(
  {
    className,
    children,
    hover = false,
    interactive = false,
    onClick,
    ...props
  },
  ref,
) {
  const resolvedInteractive = interactive || Boolean(onClick);
  return (
    <div
      ref={ref}
      onClick={onClick}
      className={[
        getCardClass({ hover, interactive: resolvedInteractive }),
        className,
      ]
        .filter(Boolean)
        .join(" ")}
      {...props}
    >
      {children}
    </div>
  );
});
