// packages/react-pro/src/components/DataTable/DataTable.tsx
import * as React from "react";

type DataTableProps = { columns: string[]; rows: Array<Record<string, string | number>> };

export function DataTable({ columns, rows }: DataTableProps) {
  return (
    <table>
      <thead><tr>{columns.map((c) => <th key={c}>{c}</th>)}</tr></thead>
      <tbody>{rows.map((r, i) => <tr key={i}>{columns.map((c) => <td key={c}>{String(r[c] ?? "")}</td>)}</tr>)}</tbody>
    </table>
  );
}

// packages/svelte-pro/src/components/DataTable.svelte
<script lang="ts">
  export let columns: Array<{ key: string; label: string }> = [];
  export let rows: Record<string, string | number>[] = [];
</script>

<div class="sm-data-table">
  <table>
    <thead><tr>{#each columns as column}<th>{column.label}</th>{/each}</tr></thead>
    <tbody>
      {#each rows as row}
        <tr>{#each columns as column}<td>{row[column.key]}</td>{/each}</tr>
      {/each}
    </tbody>
  </table>
</div>
