// packages/vue-pro/src/components/DataTable/DataTable.vue
<template>
  <div class="sm-data-table">
    <table>
      <thead><tr><th v-for="column in columns" :key="column.key">{{ column.label }}</th></tr></thead>
      <tbody>
        <tr v-for="(row, idx) in rows" :key="idx">
          <td v-for="column in columns" :key="column.key">{{ row[column.key] }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">
defineProps<{ columns: Array<{ key: string; label: string }>; rows: Record<string, string | number>[] }>();
</script>

// packages/svelte-pro/src/components/DataTable.svelte
<script lang="ts">
  export let columns: Array<{ key: string; label: string }> = [];
  export let rows: Record<string, string | number>[] = [];
</script>

<div class="sm-data-table">
  <table>
    <thead><tr>{#each columns as column}<th>{column.label}</th>{/each}</tr></thead>
    <tbody>
      {#each rows as row}
        <tr>{#each columns as column}<td>{row[column.key]}</td>{/each}</tr>
      {/each}
    </tbody>
  </table>
</div>
